const votersEvent = {
    INITIALIZE: 'VOTERS/INITIALIZE',
    FETCH_VOTERS_REQUEST: 'VOTERS/FETCH_VOTERS_REQUEST',
    FETCH_VOTERS_SUCCESS: 'VOTERS/FETCH_VOTERS_SUCCESS',
    FILTER_CHANGED: 'VOTERS/FILTER_CHANGED',
    UPDATE_VOTER_EDITS: 'VOTERS/UPDATE_VOTER_EDITS',
    SET_VOTERS_REQUEST: 'VOTERS/SET_VOTERS_REQUEST',
    ERROR_ADDED: 'VOTERS/ERROR_ADDED',
    CLEAR_ERRORS: 'VOTERS/CLEAR_ERRORS'
}

export default votersEvent
