const votersEvent = {
    SET_ELECTION_NAME: 'VOTERS/SET_ELECTION_NAME',
    FETCH_VOTERS_REQUEST: 'VOTERS/FETCH_VOTERS_REQUEST',
    FETCH_VOTERS_SUCCESS: 'VOTERS/FETCH_VOTERS_SUCCESS',
    UPDATE_VOTER_EDITS: 'VOTERS/UPDATE_VOTER_EDITS',
    SET_VOTERS_REQUEST: 'VOTERS/SET_VOTERS_REQUEST',
    ERROR_ADDED: 'VOTERS/ERROR_ADDED',
    CLEAR_ERRORS: 'VOTERS/CLEAR_ERRORS'
}

export default votersEvent
