const electionEvent = {
    FETCH_ELECTION_REQUEST: 'ELECTION/FETCH_ELECTION_REQUEST',
    FETCH_ELECTION_SUCCESS: 'ELECTION/FETCH_ELECTION_SUCCESS',
    DELETE_ELECTION_REQUEST: 'ELECTION/DELETE_ELECTION_REQUEST',
    UPDATE_ELECTION_REQUEST: 'ELECTION/UPDATE_ELECTION_REQUEST',
    UPDATE_ELECTION_EDITS: 'ELECTION/UPDATE_ELECTION_EDITS',
    ERROR_ADDED: 'ELECTION/ERROR_ADDED',
    GENERIC_ERROR: 'ELECTION/GENERIC_ERROR'
}
export default electionEvent
