const electionEvent = {
    FETCH_ELECTION_REQUEST: 'ELECTION/FETCH_ELECTION_REQUEST',
    FETCH_ELECTION_SUCCESS: 'ELECTION/FETCH_ELECTION_SUCCESS',
    DELETE_ELECTION_REQUEST: 'ELECTION/DELETE_ELECTION_REQUEST',
    UPDATE_ELECTION_REQUEST: 'ELECTION/UPDATE_ELECTION_REQUEST',
    UPDATE_ELECTION_EDITS: 'ELECTION/UPDATE_ELECTION_EDITS',
    LAUNCH_ELECTION_REQUEST:'ELECTION/LAUNCH_ELECTION_REQUEST',
    FINALIZE_ELECTION_REQUEST: 'ELECTION/FINALIZE_ELECTION_REQUEST',
    ERROR_ADDED: 'ELECTION/ERROR_ADDED',
    CLEAR_ERRORS: 'ELECTION/CLEAR_ERRORS'
}
export default electionEvent
