const dashboardEvent = {
    LOGOUT_REQUEST: 'DASHBOARD/LOGOUT',
    NAVIGATE: 'DASHBOARD/NAVIGATE',
    ERROR_ADDED: 'DASHBOARD/ERROR_ADDED',
    GENERIC_ERROR: 'DASHBOARD/GENERIC_ERROR'
}

export default dashboardEvent
