const dashboardEvent = {
    INITIALIZE: 'DASHBOARD/INITIALIZE',
    LOGOUT_REQUEST: 'DASHBOARD/LOGOUT',
    FETCH_COUNTS_REQUEST: 'DASHBOARD/FETCH_COUNTS_REQUEST',
    FETCH_COUNTS_SUCCESS: 'DASHBOARD/FETCH_COUNTS_SUCCESS',
    ERROR_ADDED: 'DASHBOARD/ERROR_ADDED',
    CLEAR_ERRORS: 'DASHBOARD/CLEAR_ERRORS'
}

export default dashboardEvent
