const dashboardEvent = {
    LOGOUT_REQUEST: 'DASHBOARD/LOGOUT',
    FETCH_NAME_REQUEST: 'DASHBOARD/FETCH_NAME_REQUEST',
    FETCH_NAME_SUCCESS: 'DASHBOARD/FETCH_NAME_SUCCESS',
    ERROR_ADDED: 'DASHBOARD/ERROR_ADDED',
    GENERIC_ERROR: 'DASHBOARD/GENERIC_ERROR'
}

export default dashboardEvent
