const changePasswordEvent = {
    INITIALIZE: 'CHANGE_PASSWORD/INITIALIZE',
    PASSWORD_CHANGED: 'CHANGE_PASSWORD/PASSWORD_CHANGED',
    CONFIRMATION_PASSWORD_CHANGED: 'CHANGE_PASSWORD/CONFIRMATION_PASSWORD_CHANGED',
    PASSWORD_DOES_NOT_MATCH_CONFIRMATION_PASSWORD: 'CHANGE_PASSWORD/PASSWORD_DOES_NOT_MATCH_CONFIRMATION_PASSWORD',
    CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD/CHANGE_PASSWORD_REQUEST',
    ERROR_ADDED: 'CHANGE_PASSWORD/ERROR_ADDED',
    CLEAR_ERRORS: 'CHANGE_PASSWORD/CLEAR_ERRORS'
}

export default changePasswordEvent
