const tablesEvent = {
    INITIALIZE: 'TABLES/INITIALIZE',
    SET_TABLE_DATA: 'TABLES/SET_TABLE_DATA',
    ERROR_ADDED: 'TABLES/ERROR_ADDED',
    CLEAR_ERRORS: 'TABLES/CLEAR_ERRORS'
}

export default tablesEvent
