const tablesEvent = {
    FETCH_TABLE_NAMES_REQUEST: 'TABLES/FETCH_TABLE_NAMES_REQUEST',
    FETCH_TABLE_NAMES_SUCCESS: 'TABLES/FETCH_TABLE_NAMES_SUCCESS',
    FETCH_TABLE_REQUEST: 'TABLES/FETCH_TABLE_REQUEST',
    FETCH_TABLE_SUCCESS: 'TABLES/FETCH_TABLE_SUCCESS',
    SELECTED_TABLE_CHANGED: 'TABLES/SELECTED_TABLE_CHANGED',
    ERROR_ADDED: 'TABLES/ERROR_ADDED',
    GENERIC_ERROR: 'TABLES/GENERIC_ERROR'
}

export default tablesEvent
