const tablesEvent = {
    INITIALIZE: 'TABLES/INITIALIZE',
    FETCH_TABLE_NAMES_REQUEST: 'TABLES/FETCH_TABLE_NAMES_REQUEST',
    FETCH_TABLE_NAMES_SUCCESS: 'TABLES/FETCH_TABLE_NAMES_SUCCESS',
    FETCH_TABLE_REQUEST: 'TABLES/FETCH_TABLE_REQUEST',
    FETCH_TABLE_SUCCESS: 'TABLES/FETCH_TABLE_SUCCESS',
    SELECTED_TABLE_CHANGED: 'TABLES/SELECTED_TABLE_CHANGED',
    ERROR_ADDED: 'TABLES/ERROR_ADDED',
    CLEAR_ERRORS: 'TABLES/CLEAR_ERRORS'
}

export default tablesEvent
