const candidatesEvent = {
    FETCH_CANDIDATES_REQUEST: 'CANDIDATES/FETCH_CANDIDATES_REQUEST',
    CHANGE_CANDIDATES: 'CANDIDATES/CHANGE_CANDIDATES',
    UPDATE_CANDIDATES_REQUEST: 'CANDIDATES/UPDATE_CANDIDATES_REQUEST',
    SET_ELECTION_NAME: 'CANDIDATES/SET_ELECTION_NAME',
    ERROR_ADDED: 'CANDIDATES/ERROR_ADDED',
    CLEAR_ERRORS: 'CANDIDATES/CLEAR_ERRORS'
}

export default candidatesEvent
