const candidatesEvent = {
    FETCH_CANDIDATES_REQUEST: 'CANDIDATES/FETCH_CANDIDATES_REQUEST',
    FETCH_CANDIDATES_SUCCESS: 'CANDIDATES/FETCH_CANDIDATES_SUCCESS',
    UPDATE_CANDIDATE_EDITS: 'CANDIDATES/UPDATE_CANDIDATE_EDITS',
    SET_CANDIDATES_REQUEST: 'CANDIDATES/SET_CANDIDATES_REQUEST',
    SET_ELECTION_NAME: 'CANDIDATES/SET_ELECTION_NAME',
    ERROR_ADDED: 'CANDIDATES/ERROR_ADDED',
    CLEAR_ERRORS: 'CANDIDATES/CLEAR_ERRORS'
}

export default candidatesEvent
