const debugTablesEvent = {
    INITIALIZE: 'DEBUG_TABLES/INITIALIZE',
    SET_TABLE_DATA: 'DEBUG_TABLES/SET_TABLE_DATA',
    ERROR_ADDED: 'DEBUG_TABLES/ERROR_ADDED',
    CLEAR_ERRORS: 'DEBUG_TABLES/CLEAR_ERRORS'
}

export default debugTablesEvent
