const debugTablesEvent = {
    FETCH_TABLE_NAMES_REQUEST: 'DEBUG_TABLES/FETCH_TABLE_NAMES_REQUEST',
    FETCH_TABLE_NAMES_SUCCESS: 'DEBUG_TABLES/FETCH_TABLE_NAMES_SUCCESS',
    FETCH_TABLE_REQUEST: 'DEBUG_TABLES/FETCH_TABLE_REQUEST',
    FETCH_TABLE_SUCCESS: 'DEBUG_TABLES/FETCH_TABLE_SUCCESS',
    SELECTED_TABLE_CHANGED: 'DEBUG_TABLES/SELECTED_TABLE_CHANGED',
    ERROR_ADDED: 'DEBUG_TABLES/ERROR_ADDED',
    CLEAR_ERRORS: 'DEBUG_TABLES/CLEAR_ERRORS'
}

export default debugTablesEvent
