const manageUsersEvent = {
    FETCH_USERS_REQUEST: 'MANAGE_USERS/FETCH_USERS_REQUEST',
    USERS_CHANGED: 'MANAGE_USERS/FETCH_USERS_SUCCESS',
    UPDATE_USER_ROLE_REQUEST: 'MANAGE_USERS/UPDATE_USER_ROLE_REQUEST',
    NAVIGATE: 'MANAGE_USERS/NAVIGATE',
    ERROR_ADDED: 'MANAGE_USERS/ERROR_ADDED',
    GENERIC_ERROR: 'MANAGE_USERS/GENERIC_ERROR'
}

export default manageUsersEvent
