const manageUsersEvent = {
    INITIALIZE: 'MANAGE_USERS/INITIALIZE',
    FETCH_USERS_REQUEST: 'MANAGE_USERS/FETCH_USERS_REQUEST',
    USERS_CHANGED: 'MANAGE_USERS/FETCH_USERS_SUCCESS',
    UPDATE_USER_ROLE_REQUEST: 'MANAGE_USERS/UPDATE_USER_ROLE_REQUEST',
    ERROR_ADDED: 'MANAGE_USERS/ERROR_ADDED',
    CLEAR_ERRORS: 'MANAGE_USERS/CLEAR_ERRORS'
}

export default manageUsersEvent
