const userEvent = {
    INITIALIZE: 'USER/INITIALIZE',
    NAME_CHANGED: 'USER/NAME_CHANGED',
    EMAIL_CHANGED: 'USER/EMAIL_CHANGED',
    UPDATE_USER_REQUEST: 'USER/UPDATE_USER_REQUEST',
    FETCH_USER_REQUEST: 'USER/FETCH_USER_REQUEST',
    FETCH_USER_SUCCESS: 'USER/FETCH_USER_SUCCESS',
    ERROR_ADDED: 'USER/ERROR_ADDED',
    CLEAR_ERRORS: 'USER/CLEAR_ERRORS'
}

export default userEvent
