const ballotEvent = {
    FETCH_BALLOT_REQUEST: 'BALLOT/FETCH_BALLOT_REQUEST',
    FETCH_BALLOT_SUCCESS: 'BALLOT/FETCH_BALLOT_SUCCESS',
    CAST_BALLOT_REQUEST: 'BALLOT/CAST_BALLOT_REQUEST',
    CAST_BALLOT_SUCCESS: 'BALLOT/CAST_BALLOT_SUCCESS',
    UPDATE_BALLOT_EDITS: 'BALLOT/UPDATE_BALLOT_EDITS',
    UPDATE_RANK: 'BALLOT/UPDATE_RANK',
    NAVIGATE_ELECTION: 'BALLOT/NAVIGATE_ELECTION',
    NAVIGATE_DASHBOARD: 'BALLOT/NAVIGATE_DASHBOARD',
    ERROR_ADDED: 'BALLOT/ERROR_ADDED'
}

export default ballotEvent
