const ballotEvent = {
    INITIALIZE: 'BALLOT/INITIALIZE',
    FETCH_BALLOT_REQUEST: 'BALLOT/FETCH_BALLOT_REQUEST',
    FETCH_BALLOT_SUCCESS: 'BALLOT/FETCH_BALLOT_SUCCESS',
    CAST_BALLOT_REQUEST: 'BALLOT/CAST_BALLOT_REQUEST',
    CAST_BALLOT_SUCCESS: 'BALLOT/CAST_BALLOT_SUCCESS',
    SELECT_CANDIDATE: 'BALLOT/SELECT_CANDIDATE',
    CLEAR_BALLOT: 'BALLOT/CLEAR_BALLOT',
    ERROR_ADDED: 'BALLOT/ERROR_ADDED',
    CLEAR_ERRORS: 'BALLOT/CLEAR_ERRORS'
}

export default ballotEvent
