const loginEvent = {
    INITIALIZE: 'LOGIN/INITIALIZE',
    NAME_OR_EMAIL_CHANGED: 'LOGIN/NAME_OR_EMAIL_CHANGED',
    PASSWORD_CHANGED: 'LOGIN/PASSWORD_CHANGED',
    LOGIN_REQUEST: 'LOGIN/LOGIN_REQUEST',
    ERROR_ADDED: 'LOGIN/ERROR_ADDED',
    CLEAR_ERRORS: 'LOGIN/CLEAR_ERRORS'
}

export default loginEvent
