const electionsEvent = {
    FETCH_ELECTIONS_REQUEST: 'ELECTIONS/FETCH_ELECTIONS_REQUEST',
    FETCH_ELECTIONS_SUCCESS: 'ELECTIONS/FETCH_ELECTIONS_SUCCESS',
    ADD_ELECTION_REQUEST: 'ELECTIONS/ADD_ELECTION_REQUEST',
    ADD_ELECTION_SUCCESS: 'ELECTIONS/ADD_ELECTION_SUCCESS',
    ELECTION_NAME_CHANGED: 'ELECTIONS/ELECTION_NAME_CHANGED',
    ERROR_ADDED: 'ELECTIONS/ERROR_ADDED'
}

export default electionsEvent
