const usersEvent = {
    INITIALIZE: 'USERS/INITIALIZE',
    FETCH_USERS_REQUEST: 'USERS/FETCH_USERS_REQUEST',
    USERS_CHANGED: 'USERS/FETCH_USERS_SUCCESS',
    UPDATE_USER_ROLE_REQUEST: 'USERS/UPDATE_USER_ROLE_REQUEST',
    ERROR_ADDED: 'USERS/ERROR_ADDED',
    CLEAR_ERRORS: 'USERS/CLEAR_ERRORS'
}

export default usersEvent
