const eventsEvent = {
    FETCH_TABLE_REQUEST: 'EVENTS/FETCH_TABLE_REQUEST',
    FETCH_TABLE_SUCCESS: 'EVENTS/FETCH_TABLE_SUCCESS',
    ERROR_ADDED: 'EVENTS/ERROR_ADDED'
}

export default eventsEvent
