const eventsEvent = {
    INITIALIZE: 'EVENTS/INITIALIZE',
    FETCH_TABLE_REQUEST: 'EVENTS/FETCH_TABLE_REQUEST',
    FETCH_TABLE_SUCCESS: 'EVENTS/FETCH_TABLE_SUCCESS',
    ERROR_ADDED: 'EVENTS/ERROR_ADDED',
    CLEAR_ERRORS: 'EVENTS/CLEAR_ERRORS'
}

export default eventsEvent
