const registerEvent = {
    NAME_CHANGED: 'REGISTER/NAME_CHANGED',
    EMAIL_CHANGED: 'REGISTER/EMAIL_CHANGED',
    PASSWORD_CHANGED: 'REGISTER/PASSWORD_CHANGED',
    CONFIRMATION_PASSWORD_CHANGED: 'REGISTER/CONFIRMATION_PASSWORD_CHANGED',
    PASSWORD_DOES_NOT_MATCH_CONFIRMATION_PASSWORD: 'REGISTER/PASSWORD_DOES_NOT_MATCH_CONFIRMATION_PASSWORD',
    REGISTER_REQUEST: 'REGISTER/REGISTER_REQUEST',
    ERROR_ADDED: 'REGISTER/ERROR_ADDED',
    CLEAR_ERRORS: 'REGISTER/CLEAR_ERRORS'
}

export default registerEvent
