const resetPasswordEvent = {
    INITIALIZE: 'RESET_PASSWORD/INITIALIZE',
    SET_MESSAGE: 'RESET_PASSWORD/SET_MESSAGE',
    EMAIL_CHANGED: 'RESET_PASSWORD/EMAIL_CHANGED',
    RESET_PASSWORD_REQUEST: 'RESET_PASSWORD/RESET_PASSWORD_REQUEST',
    ERROR_ADDED: 'RESET_PASSWORD/ERROR_ADDED',
    CLEAR_ERRORS: 'RESET_PASSWORD/CLEAR_ERRORS'
}

export default resetPasswordEvent
