const tallyEvent = {
    INITIALIZE: 'TALLY/INITIALIZE',
    FETCH_TALLY_REQUEST: 'TALLY/FETCH_TALLY_REQUEST',
    FETCH_TALLY_SUCCESS: 'TALLY/FETCH_TALLY_SUCCESS',
    ERROR_ADDED: 'TALLY/ERROR_ADDED',
    CLEAR_ERRORS: 'TALLY/CLEAR_ERRORS'
}
export default tallyEvent
