const tallyEvent = {
    FETCH_TALLY_REQUEST: 'TALLY/FETCH_TALLY_REQUEST',
    FETCH_TALLY_SUCCESS: 'TALLY/FETCH_TALLY_SUCCESS',
    NAVIGATE_ELECTION: 'TALLY/NAVIGATE_ELECTION',
    NAVIGATE_DASHBOARD: 'TALLY/NAVIGATE_DASHBOARD',
    ERROR_ADDED: 'TALLY/ERROR_ADDED'
}
export default tallyEvent
