const adminEvent = {
    FETCH_USERS_REQUEST: 'ADMIN/FETCH_USERS_REQUEST',
    USERS_CHANGED: 'ADMIN/FETCH_USERS_SUCCESS',
    UPDATE_USER_ROLE_REQUEST: 'ADMIN/UPDATE_USER_ROLE_REQUEST',
    ERROR_ADDED: 'ADMIN/ERROR_ADDED',
    GENERIC_ERROR: 'ADMIN/GENERIC_ERROR'
}

export default adminEvent
