const navigationEvent = {
    FETCH_PAGE_REQUEST: 'NAVIGATION/FETCH_PAGE_REQUEST',
    FETCH_PAGE_SUCCESS: 'NAVIGATION/FETCH_PAGE_SUCCESS',
    HISTORY: 'NAVIGATION/HISTORY',
    REDIRECT: 'NAVIGATION/REDIRECT',
    SET_URI: 'NAVIGATION/SET_URI',
    ERROR_ADDED: 'NAVIGATION/ERROR_ADDED',
    GENERIC_ERROR: 'NAVIGATION/GENERIC_ERROR'
}

export default navigationEvent
