const navigationEvent = {
    FETCH_PAGE_REQUEST: 'NAVIGATION/FETCH_PAGE_REQUEST',
    FETCH_PAGE_SUCCESS: 'NAVIGATION/FETCH_PAGE_SUCCESS',
    HISTORY: 'NAVIGATION/HISTORY',
    SET_URI: 'NAVIGATION/SET_URI',
    CLEAR_BROWSER_STATE: 'NAVIGATION/CLEAR_BROWSER_STATE',
    ERROR_ADDED: 'NAVIGATION/ERROR_ADDED',
    CLEAR_ERRORS: 'NAVIGATION/CLEAR_ERRORS'
}

export default navigationEvent
